
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Mar 03 21:03:21 CET 2025
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISTINTO = 36;
  public static final int LLCIERRE = 44;
  public static final int CCIERRE = 52;
  public static final int PCIERRE = 42;
  public static final int RESTA = 29;
  public static final int INT = 3;
  public static final int DELETE = 18;
  public static final int WRITE = 20;
  public static final int NOT = 8;
  public static final int AND = 6;
  public static final int IGUAL = 35;
  public static final int TYPE = 22;
  public static final int OR = 7;
  public static final int BOOL = 2;
  public static final int ARROBA = 48;
  public static final int CALL = 23;
  public static final int DIV = 31;
  public static final int LITENT = 24;
  public static final int SUMA = 28;
  public static final int IF = 13;
  public static final int INDIR = 49;
  public static final int EOF = 0;
  public static final int ASIG = 39;
  public static final int TRUE = 9;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int LITREAL = 25;
  public static final int COMA = 46;
  public static final int MUL = 30;
  public static final int NULL = 11;
  public static final int MENOR = 33;
  public static final int MOD = 32;
  public static final int PCOMA = 45;
  public static final int REAL = 4;
  public static final int MAYOR = 34;
  public static final int PAPERT = 41;
  public static final int ELSE = 14;
  public static final int PUNTO = 47;
  public static final int MAYORIG = 38;
  public static final int NL = 21;
  public static final int READ = 19;
  public static final int IDEN = 27;
  public static final int WHILE = 15;
  public static final int PARAMREF = 50;
  public static final int MENORIG = 37;
  public static final int LLAPERT = 43;
  public static final int PROC = 12;
  public static final int STRING = 5;
  public static final int LITCADENA = 26;
  public static final int FALSE = 10;
  public static final int STRUCT = 16;
  public static final int CAPERT = 51;
  public static final int FINASIG = 40;
}

