/* AnalizadorSintacticoTiny.java */
/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTiny.java */
package c_ast_descendente;
import asint.ClaseSemanticaTiny;
import errors.GestionErroresTiny;
import asint.SintaxisAbstractaTiny.Bloq;
import asint.SintaxisAbstractaTiny.SecDecs;
import asint.SintaxisAbstractaTiny.LDecs;
import asint.SintaxisAbstractaTiny.Dec;
import asint.SintaxisAbstractaTiny.SecIs;
import asint.SintaxisAbstractaTiny.LIs;
import asint.SintaxisAbstractaTiny.I;
import asint.SintaxisAbstractaTiny.ParamFs;
import asint.SintaxisAbstractaTiny.LParamFs;
import asint.SintaxisAbstractaTiny.ParamF;
import asint.SintaxisAbstractaTiny.ParamRs;
import asint.SintaxisAbstractaTiny.LParamRs;
import asint.SintaxisAbstractaTiny.LCampos;
import asint.SintaxisAbstractaTiny.TipoNom;
import asint.SintaxisAbstractaTiny.Tipo;
import asint.SintaxisAbstractaTiny.Exp;
import c_ast_ascendente.UnidadLexica.StringLocalizado;

public class AnalizadorSintacticoTiny implements AnalizadorSintacticoTinyConstants {
   private ClaseSemanticaTiny sem = new ClaseSemanticaTiny();

  final public Bloq analiza() throws ParseException {
    trace_call("analiza");
    try {
Bloq prog;
      prog = bloque();
      jj_consume_token(0);
{if ("" != null) return prog;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("analiza");
    }
}

  final public Bloq bloque() throws ParseException {
    trace_call("bloque");
    try {
SecDecs secdecs; SecIs secis;
      jj_consume_token(llaveApert);
      secdecs = seccion_declaraciones_opt();
      secis = seccion_instrucciones_opt();
      jj_consume_token(llaveCierre);
{if ("" != null) return sem.bloq(secdecs, secis);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("bloque");
    }
}

  final public SecDecs seccion_declaraciones_opt() throws ParseException {
    trace_call("seccion_declaraciones_opt");
    try {
LDecs ldecs;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case bool:
      case INT:
      case real:
      case string:
      case proc:
      case struct:
      case type:
      case identificador:
      case indireccion:{
        ldecs = seccion_declaraciones();
        jj_consume_token(finalAsig);
{if ("" != null) return sem.si_decs(ldecs);}
        break;
        }
      default:
        jj_la1[0] = jj_gen;
{if ("" != null) return sem.no_decs();}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("seccion_declaraciones_opt");
    }
}

  final public LDecs seccion_declaraciones() throws ParseException {
    trace_call("seccion_declaraciones");
    try {
Dec dec; LDecs r;
      dec = declaracion();
      r = resto_sd(sem.una_dec(dec));
{if ("" != null) return r;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("seccion_declaraciones");
    }
}

  final public LDecs resto_sd(LDecs rh) throws ParseException {
    trace_call("resto_sd");
    try {
Dec dec; LDecs r;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case puntoComa:{
        jj_consume_token(puntoComa);
        dec = declaracion();
        r = resto_sd(sem.muchas_decs(rh, dec));
{if ("" != null) return r;}
        break;
        }
      default:
        jj_la1[1] = jj_gen;
{if ("" != null) return rh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("resto_sd");
    }
}

  final public Dec declaracion() throws ParseException {
    trace_call("declaracion");
    try {
TipoNom tiponom; Token id; ParamFs p; Bloq bloq;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case bool:
      case INT:
      case real:
      case string:
      case struct:
      case identificador:
      case indireccion:{
        tiponom = tipo_nombre();
{if ("" != null) return (Dec)sem.dec_base(tiponom);}
        break;
        }
      case type:{
        jj_consume_token(type);
        tiponom = tipo_nombre();
{if ("" != null) return (Dec)sem.dec_type(tiponom);}
        break;
        }
      case proc:{
        jj_consume_token(proc);
        id = jj_consume_token(identificador);
        p = parametros_formales();
        bloq = bloque();
{if ("" != null) return (Dec)sem.dec_proc(id.image, p, bloq).ponFila(id.beginLine).ponCol(id.beginColumn);}
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("declaracion");
    }
}

  final public ParamFs parametros_formales() throws ParseException {
    trace_call("parametros_formales");
    try {
ParamFs p;
      jj_consume_token(parenApert);
      p = lista_parametros_opt();
      jj_consume_token(parenCierre);
{if ("" != null) return p;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("parametros_formales");
    }
}

  final public ParamFs lista_parametros_opt() throws ParseException {
    trace_call("lista_parametros_opt");
    try {
LParamFs lp;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case bool:
      case INT:
      case real:
      case string:
      case struct:
      case identificador:
      case indireccion:{
        lp = lista_parametros();
{if ("" != null) return (ParamFs)sem.si_params_f(lp);}
        break;
        }
      default:
        jj_la1[3] = jj_gen;
{if ("" != null) return (ParamFs)sem.no_params_f();}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("lista_parametros_opt");
    }
}

  final public LParamFs lista_parametros() throws ParseException {
    trace_call("lista_parametros");
    try {
LParamFs lp; ParamF p;
      p = parametro();
      lp = resto_lp(sem.un_param_f(p));
{if ("" != null) return lp;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("lista_parametros");
    }
}

  final public LParamFs resto_lp(LParamFs rh) throws ParseException {
    trace_call("resto_lp");
    try {
LParamFs lp; ParamF p;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case coma:{
        jj_consume_token(coma);
        p = parametro();
        lp = resto_lp(sem.muchos_params_f(rh, p));
{if ("" != null) return lp;}
        break;
        }
      default:
        jj_la1[4] = jj_gen;
{if ("" != null) return rh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("resto_lp");
    }
}

  final public ParamF parametro() throws ParseException {
    trace_call("parametro");
    try {
Tipo t; ParamF r;
      t = tipo();
      r = resto_parametro(t);
{if ("" != null) return r;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("parametro");
    }
}

  final public ParamF resto_parametro(Tipo th) throws ParseException {
    trace_call("resto_parametro");
    try {
Token id;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case paramRef:{
        jj_consume_token(paramRef);
        id = jj_consume_token(identificador);
{if ("" != null) return (ParamF)sem.si_refparam_f(th, id.image).ponFila(id.beginLine).ponCol(id.beginColumn);}
        break;
        }
      case identificador:{
        id = jj_consume_token(identificador);
{if ("" != null) return (ParamF)sem.no_refparam_f(th, id.image).ponFila(id.beginLine).ponCol(id.beginColumn);}
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("resto_parametro");
    }
}

  final public TipoNom tipo_nombre() throws ParseException {
    trace_call("tipo_nombre");
    try {
Tipo t; Token id;
      t = tipo();
      id = jj_consume_token(identificador);
{if ("" != null) return (TipoNom)sem.tipo_nombre(t, id.image).ponFila(id.beginLine).ponCol(id.beginColumn);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("tipo_nombre");
    }
}

  final public Tipo tipo() throws ParseException {
    trace_call("tipo");
    try {
Tipo t;
      t = tipo0();
{if ("" != null) return t;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("tipo");
    }
}

  final public Tipo tipo0() throws ParseException {
    trace_call("tipo0");
    try {
Tipo t; Tipo r;
      t = tipo1();
      r = resto_tipo0(t);
{if ("" != null) return r;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("tipo0");
    }
}

  final public Tipo resto_tipo0(Tipo th) throws ParseException {
    trace_call("resto_tipo0");
    try {
Tipo r; Token id;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case corcheteApert:{
        jj_consume_token(corcheteApert);
        id = jj_consume_token(literalEntero);
        jj_consume_token(corcheteCierre);
        r = resto_tipo0((Tipo)sem.tipo_array(th, id.image).ponFila(id.beginLine).ponCol(id.beginColumn));
{if ("" != null) return r;}
        break;
        }
      default:
        jj_la1[6] = jj_gen;
{if ("" != null) return th;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("resto_tipo0");
    }
}

  final public Tipo tipo1() throws ParseException {
    trace_call("tipo1");
    try {
Tipo t;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case indireccion:{
        jj_consume_token(indireccion);
        t = tipo1();
{if ("" != null) return (Tipo)sem.tipo_indir(t);}
        break;
        }
      case bool:
      case INT:
      case real:
      case string:
      case struct:
      case identificador:{
        t = tipo_base();
{if ("" != null) return t;}
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("tipo1");
    }
}

  final public Tipo tipo_base() throws ParseException {
    trace_call("tipo_base");
    try {
LCampos lc; Token id;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case struct:{
        jj_consume_token(struct);
        jj_consume_token(llaveApert);
        lc = lista_campos();
        jj_consume_token(llaveCierre);
{if ("" != null) return (Tipo)sem.tipo_struct(lc);}
        break;
        }
      case INT:{
        jj_consume_token(INT);
{if ("" != null) return (Tipo)sem.tipo_int();}
        break;
        }
      case real:{
        jj_consume_token(real);
{if ("" != null) return (Tipo)sem.tipo_real();}
        break;
        }
      case bool:{
        jj_consume_token(bool);
{if ("" != null) return (Tipo)sem.tipo_bool();}
        break;
        }
      case string:{
        jj_consume_token(string);
{if ("" != null) return (Tipo)sem.tipo_string();}
        break;
        }
      case identificador:{
        id = jj_consume_token(identificador);
{if ("" != null) return (Tipo)sem.tipo_type(id.image).ponFila(id.beginLine).ponCol(id.beginColumn);}
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("tipo_base");
    }
}

  final public LCampos lista_campos() throws ParseException {
    trace_call("lista_campos");
    try {
TipoNom t; LCampos r;
      t = tipo_nombre();
      r = resto_lc(sem.un_campo(t));
{if ("" != null) return r;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("lista_campos");
    }
}

  final public LCampos resto_lc(LCampos th) throws ParseException {
    trace_call("resto_lc");
    try {
TipoNom t; LCampos r;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case coma:{
        jj_consume_token(coma);
        t = tipo_nombre();
        r = resto_lc(sem.muchos_campos(th, t));
{if ("" != null) return r;}
        break;
        }
      default:
        jj_la1[9] = jj_gen;
{if ("" != null) return th;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("resto_lc");
    }
}

  final public SecIs seccion_instrucciones_opt() throws ParseException {
    trace_call("seccion_instrucciones_opt");
    try {
LIs secis;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF:
      case WHILE:
      case NEW:
      case delete:
      case read:
      case write:
      case nl:
      case call:
      case llaveApert:
      case arroba:{
        secis = seccion_instrucciones();
{if ("" != null) return (SecIs)sem.si_ins(secis);}
        break;
        }
      default:
        jj_la1[10] = jj_gen;
{if ("" != null) return (SecIs)sem.no_ins();}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("seccion_instrucciones_opt");
    }
}

  final public LIs seccion_instrucciones() throws ParseException {
    trace_call("seccion_instrucciones");
    try {
LIs lis;
      lis = lista_instrucciones();
{if ("" != null) return lis;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("seccion_instrucciones");
    }
}

  final public LIs lista_instrucciones() throws ParseException {
    trace_call("lista_instrucciones");
    try {
I i; LIs lis;
      i = instruccion();
      lis = resto_li(sem.una_ins(i));
{if ("" != null) return lis;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("lista_instrucciones");
    }
}

  final public LIs resto_li(LIs lh) throws ParseException {
    trace_call("resto_li");
    try {
I i; LIs lis;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case puntoComa:{
        jj_consume_token(puntoComa);
        i = instruccion();
        lis = resto_li(sem.muchas_ins(lh, i));
{if ("" != null) return lis;}
        break;
        }
      default:
        jj_la1[11] = jj_gen;
{if ("" != null) return lh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("resto_li");
    }
}

  final public I instruccion() throws ParseException {
    trace_call("instruccion");
    try {
Exp e; I i; I r; ParamRs params; Token id; Bloq bloq;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case arroba:{
        jj_consume_token(arroba);
        e = expresion();
{if ("" != null) return (I)sem.ins_eval(e);}
        break;
        }
      case IF:{
        i = if_ins();
        r = resto_ii(i);
{if ("" != null) return r;}
        break;
        }
      case WHILE:{
        jj_consume_token(WHILE);
        e = expresion();
        bloq = bloque();
{if ("" != null) return (I)sem.ins_while(e, bloq);}
        break;
        }
      case read:{
        jj_consume_token(read);
        e = expresion();
{if ("" != null) return (I)sem.ins_read(e);}
        break;
        }
      case write:{
        jj_consume_token(write);
        e = expresion();
{if ("" != null) return (I)sem.ins_write(e);}
        break;
        }
      case nl:{
        jj_consume_token(nl);
{if ("" != null) return (I)sem.ins_nl();}
        break;
        }
      case NEW:{
        jj_consume_token(NEW);
        e = expresion();
{if ("" != null) return (I)sem.ins_new(e);}
        break;
        }
      case delete:{
        jj_consume_token(delete);
        e = expresion();
{if ("" != null) return (I)sem.ins_delete(e);}
        break;
        }
      case call:{
        jj_consume_token(call);
        id = jj_consume_token(identificador);
        params = parametros_reales();
{if ("" != null) return (I)sem.ins_call(id.image, params).ponFila(id.beginLine).ponCol(id.beginColumn);}
        break;
        }
      case llaveApert:{
        bloq = bloque();
{if ("" != null) return (I)sem.ins_bloque(bloq);}
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("instruccion");
    }
}

  final public I resto_ii(I ih) throws ParseException {
    trace_call("resto_ii");
    try {
Bloq bloq;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ELSE:{
        jj_consume_token(ELSE);
        bloq = bloque();
{if ("" != null) return (I)sem.ins_if_else(ih, bloq);}
        break;
        }
      default:
        jj_la1[13] = jj_gen;
{if ("" != null) return ih;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("resto_ii");
    }
}

  final public I if_ins() throws ParseException {
    trace_call("if_ins");
    try {
Exp e; Bloq bloq;
      jj_consume_token(IF);
      e = expresion();
      bloq = bloque();
{if ("" != null) return (I)sem.ins_if(e, bloq);}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("if_ins");
    }
}

  final public ParamRs parametros_reales() throws ParseException {
    trace_call("parametros_reales");
    try {
ParamRs p;
      jj_consume_token(parenApert);
      p = lista_expresiones_opt();
      jj_consume_token(parenCierre);
{if ("" != null) return p;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("parametros_reales");
    }
}

  final public ParamRs lista_expresiones_opt() throws ParseException {
    trace_call("lista_expresiones_opt");
    try {
LParamRs p;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case not:
      case TRUE:
      case FALSE:
      case NULL:
      case literalEntero:
      case literalReal:
      case identificador:
      case literalCadena:
      case resta:
      case parenApert:{
        p = lista_expresiones();
{if ("" != null) return (ParamRs)sem.si_params_r(p);}
        break;
        }
      default:
        jj_la1[14] = jj_gen;
{if ("" != null) return (ParamRs)sem.no_params_r();}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("lista_expresiones_opt");
    }
}

  final public LParamRs lista_expresiones() throws ParseException {
    trace_call("lista_expresiones");
    try {
LParamRs r; Exp e;
      e = expresion();
      r = resto_le(sem.un_param_r(e));
{if ("" != null) return r;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("lista_expresiones");
    }
}

  final public LParamRs resto_le(LParamRs rh) throws ParseException {
    trace_call("resto_le");
    try {
LParamRs r; Exp e;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case coma:{
        jj_consume_token(coma);
        e = expresion();
        r = resto_le(sem.muchos_params_r(rh, e));
{if ("" != null) return r;}
        break;
        }
      default:
        jj_la1[15] = jj_gen;
{if ("" != null) return rh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("resto_le");
    }
}

  final public Exp expresion() throws ParseException {
    trace_call("expresion");
    try {
Exp e;
      e = E0();
{if ("" != null) return e;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("expresion");
    }
}

  final public Exp E0() throws ParseException {
    trace_call("E0");
    try {
Exp e, r;
      e = E1();
      r = resto_E0(e);
{if ("" != null) return r;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("E0");
    }
}

  final public Exp resto_E0(Exp eh) throws ParseException {
    trace_call("resto_E0");
    try {
Exp e; Token op;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case asig:{
        op = jj_consume_token(asig);
        e = E0();
{if ("" != null) return (Exp)sem.mkopbin(op.image, eh, e).ponFila(op.beginLine).ponCol(op.beginColumn);}
        break;
        }
      default:
        jj_la1[16] = jj_gen;
{if ("" != null) return eh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("resto_E0");
    }
}

  final public Exp E1() throws ParseException {
    trace_call("E1");
    try {
Exp e, r;
      e = E2();
      r = resto_E1(e);
{if ("" != null) return r;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("E1");
    }
}

  final public Exp resto_E1(Exp eh) throws ParseException {
    trace_call("resto_E1");
    try {
Exp e, r; Token op;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case menor:
      case mayor:
      case igual:
      case distinto:
      case menorIgual:
      case mayorIgual:{
        op = op_relacional();
        e = E2();
        r = resto_E1((Exp)sem.mkopbin(op.image, eh, e).ponFila(op.beginLine).ponCol(op.beginColumn));
{if ("" != null) return r;}
        break;
        }
      default:
        jj_la1[17] = jj_gen;
{if ("" != null) return eh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("resto_E1");
    }
}

  final public Exp E2() throws ParseException {
    trace_call("E2");
    try {
Exp e, rf, rr;
      e = E3();
      rf = resto_E2_F(e);
      rr = resto_E2_R((Exp)rf);
{if ("" != null) return rr;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("E2");
    }
}

  final public Exp resto_E2_R(Exp eh) throws ParseException {
    trace_call("resto_E2_R");
    try {
Exp e, r; Token op;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case suma:{
        op = jj_consume_token(suma);
        e = E3();
        r = resto_E2_R((Exp)sem.mkopbin(op.image, eh, e).ponFila(op.beginLine).ponCol(op.beginColumn));
{if ("" != null) return r;}
        break;
        }
      default:
        jj_la1[18] = jj_gen;
{if ("" != null) return eh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("resto_E2_R");
    }
}

  final public Exp resto_E2_F(Exp eh) throws ParseException {
    trace_call("resto_E2_F");
    try {
Exp e; Token op;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case resta:{
        op = jj_consume_token(resta);
        e = E3();
{if ("" != null) return (Exp)sem.mkopbin(op.image, eh, e).ponFila(op.beginLine).ponCol(op.beginColumn);}
        break;
        }
      default:
        jj_la1[19] = jj_gen;
{if ("" != null) return eh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("resto_E2_F");
    }
}

  final public Exp E3() throws ParseException {
    trace_call("E3");
    try {
Exp e, r;
      e = E4();
      r = resto_E3(e);
{if ("" != null) return r;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("E3");
    }
}

  final public Exp resto_E3(Exp eh) throws ParseException {
    trace_call("resto_E3");
    try {
Exp e, r; Token op;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case and:{
        op = jj_consume_token(and);
        e = E3();
{if ("" != null) return (Exp)sem.exp_and(eh, e).ponFila(op.beginLine).ponCol(op.beginColumn);}
        break;
        }
      case or:{
        op = jj_consume_token(or);
        e = E4();
{if ("" != null) return (Exp)sem.exp_or(eh, e).ponFila(op.beginLine).ponCol(op.beginColumn);}
        break;
        }
      default:
        jj_la1[20] = jj_gen;
{if ("" != null) return eh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("resto_E3");
    }
}

  final public Exp E4() throws ParseException {
    trace_call("E4");
    try {
Exp e, r;
      e = E5();
      r = resto_E4(e);
{if ("" != null) return r;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("E4");
    }
}

  final public Exp resto_E4(Exp eh) throws ParseException {
    trace_call("resto_E4");
    try {
Exp e, r; Token op;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case mul:
      case div:
      case mod:{
        op = op_mult();
        e = E5();
        r = resto_E4((Exp)sem.mkopbin(op.image, eh, e).ponFila(op.beginLine).ponCol(op.beginColumn));
{if ("" != null) return r;}
        break;
        }
      default:
        jj_la1[21] = jj_gen;
{if ("" != null) return eh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("resto_E4");
    }
}

  final public Exp E5() throws ParseException {
    trace_call("E5");
    try {
Exp e; Token op;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case resta:{
        op = jj_consume_token(resta);
        e = E5();
{if ("" != null) return (Exp)sem.exp_menos(e).ponFila(op.beginLine).ponCol(op.beginColumn);}
        break;
        }
      case not:{
        op = jj_consume_token(not);
        e = E5();
{if ("" != null) return (Exp)sem.exp_not(e).ponFila(op.beginLine).ponCol(op.beginColumn);}
        break;
        }
      case TRUE:
      case FALSE:
      case NULL:
      case literalEntero:
      case literalReal:
      case identificador:
      case literalCadena:
      case parenApert:{
        e = E6();
{if ("" != null) return e;}
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("E5");
    }
}

  final public Exp E6() throws ParseException {
    trace_call("E6");
    try {
Exp e, r;
      e = E7();
      r = resto_E6(e);
{if ("" != null) return r;}
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("E6");
    }
}

  final public Exp resto_E6(Exp eh) throws ParseException {
    trace_call("resto_E6");
    try {
Exp e, r; Token op;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case corcheteApert:{
        op = jj_consume_token(corcheteApert);
        e = expresion();
        jj_consume_token(corcheteCierre);
        r = resto_E6((Exp)sem.exp_index(eh, e).ponFila(op.beginLine).ponCol(op.beginColumn));
{if ("" != null) return r;}
        break;
        }
      case punto:{
        jj_consume_token(punto);
        op = jj_consume_token(identificador);
        r = resto_E6((Exp)sem.exp_reg(eh, op.image).ponFila(op.beginLine).ponCol(op.beginColumn));
{if ("" != null) return r;}
        break;
        }
      case indireccion:{
        op = jj_consume_token(indireccion);
        r = resto_E6((Exp)sem.exp_indir(eh).ponFila(op.beginLine).ponCol(op.beginColumn));
{if ("" != null) return r;}
        break;
        }
      default:
        jj_la1[23] = jj_gen;
{if ("" != null) return eh;}
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("resto_E6");
    }
}

  final public Exp E7() throws ParseException {
    trace_call("E7");
    try {
Exp e;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TRUE:
      case FALSE:
      case NULL:
      case literalEntero:
      case literalReal:
      case identificador:
      case literalCadena:{
        e = expresion_basica();
{if ("" != null) return e;}
        break;
        }
      case parenApert:{
        jj_consume_token(parenApert);
        e = E0();
        jj_consume_token(parenCierre);
{if ("" != null) return e;}
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("E7");
    }
}

  final public Exp expresion_basica() throws ParseException {
    trace_call("expresion_basica");
    try {
Token op;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case literalEntero:{
        op = jj_consume_token(literalEntero);
{if ("" != null) return (Exp)sem.exp_entero(op.image).ponFila(op.beginLine).ponCol(op.beginColumn);}
        break;
        }
      case literalReal:{
        op = jj_consume_token(literalReal);
{if ("" != null) return (Exp)sem.exp_real(op.image).ponFila(op.beginLine).ponCol(op.beginColumn);}
        break;
        }
      case TRUE:{
        op = jj_consume_token(TRUE);
{if ("" != null) return (Exp)sem.exp_true().ponFila(op.beginLine).ponCol(op.beginColumn);}
        break;
        }
      case FALSE:{
        op = jj_consume_token(FALSE);
{if ("" != null) return (Exp)sem.exp_false().ponFila(op.beginLine).ponCol(op.beginColumn);}
        break;
        }
      case literalCadena:{
        op = jj_consume_token(literalCadena);
{if ("" != null) return (Exp)sem.exp_cadena(op.image).ponFila(op.beginLine).ponCol(op.beginColumn);}
        break;
        }
      case identificador:{
        op = jj_consume_token(identificador);
{if ("" != null) return (Exp)sem.exp_iden(op.image).ponFila(op.beginLine).ponCol(op.beginColumn);}
        break;
        }
      case NULL:{
        op = jj_consume_token(NULL);
{if ("" != null) return (Exp)sem.exp_null().ponFila(op.beginLine).ponCol(op.beginColumn);}
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("expresion_basica");
    }
}

  final public Token op_relacional() throws ParseException {
    trace_call("op_relacional");
    try {
Token op;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case menor:{
        op = jj_consume_token(menor);
{if ("" != null) return op;}
        break;
        }
      case menorIgual:{
        op = jj_consume_token(menorIgual);
{if ("" != null) return op;}
        break;
        }
      case mayor:{
        op = jj_consume_token(mayor);
{if ("" != null) return op;}
        break;
        }
      case mayorIgual:{
        op = jj_consume_token(mayorIgual);
{if ("" != null) return op;}
        break;
        }
      case igual:{
        op = jj_consume_token(igual);
{if ("" != null) return op;}
        break;
        }
      case distinto:{
        op = jj_consume_token(distinto);
{if ("" != null) return op;}
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("op_relacional");
    }
}

  final public Token op_mult() throws ParseException {
    trace_call("op_mult");
    try {
Token op;
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case mul:{
        op = jj_consume_token(mul);
{if ("" != null) return op;}
        break;
        }
      case div:{
        op = jj_consume_token(div);
{if ("" != null) return op;}
        break;
        }
      case mod:{
        op = jj_consume_token(mod);
{if ("" != null) return op;}
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("op_mult");
    }
}

  /** Generated Token Manager. */
  public AnalizadorSintacticoTinyTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[28];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x20881e00,0x0,0x20881e00,0x801e00,0x0,0x0,0x0,0x801e00,0x801e00,0x0,0x5f500000,0x0,0x5f500000,0x200000,0x80078000,0x0,0x0,0x0,0x0,0x0,0x6000,0x0,0x80078000,0x0,0x80070000,0x80070000,0x0,0x0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x1000002,0x100000,0x1000002,0x1000002,0x200000,0x2000002,0x4000000,0x1000002,0x2,0x200000,0x840000,0x100000,0x840000,0x0,0x10017,0x200000,0x4000,0x3f00,0x8,0x10,0x0,0xe0,0x10017,0x5400000,0x10007,0x7,0x3f00,0xe0,};
	}

  {
      enable_tracing();
  }
  /** Constructor with InputStream. */
  public AnalizadorSintacticoTiny(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public AnalizadorSintacticoTiny(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new AnalizadorSintacticoTinyTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 28; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 28; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public AnalizadorSintacticoTiny(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new AnalizadorSintacticoTinyTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 28; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new AnalizadorSintacticoTinyTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 28; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public AnalizadorSintacticoTiny(AnalizadorSintacticoTinyTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 28; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(AnalizadorSintacticoTinyTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 28; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   trace_token(token, "");
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	   trace_token(token, " (in getNextToken)");
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[60];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 28; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 60; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  private int trace_indent = 0;
/** Enable tracing. */
  final public void enable_tracing() {
	 trace_enabled = true;
  }

/** Disable tracing. */
  final public void disable_tracing() {
	 trace_enabled = false;
  }

  protected void trace_call(String s) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.println("Call:	" + s);
	 }
	 trace_indent = trace_indent + 2;
  }

  protected void trace_return(String s) {
	 trace_indent = trace_indent - 2;
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.println("Return: " + s);
	 }
  }

  protected void trace_token(Token t, String where) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.print("Consumed token: <" + tokenImage[t.kind]);
	   if (t.kind != 0 && !tokenImage[t.kind].equals("\"" + t.image + "\"")) {
		 System.out.print(": \"" + TokenMgrError.addEscapes(t.image) + "\"");
	   }
	   System.out.println(" at line " + t.beginLine + " column " + t.beginColumn + ">" + where);
	 }
  }

  protected void trace_scan(Token t1, int t2) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.print("Visited token: <" + tokenImage[t1.kind]);
	   if (t1.kind != 0 && !tokenImage[t1.kind].equals("\"" + t1.image + "\"")) {
		 System.out.print(": \"" + TokenMgrError.addEscapes(t1.image) + "\"");
	   }
	   System.out.println(" at line " + t1.beginLine + " column " + t1.beginColumn + ">; Expected token: <" + tokenImage[t2] + ">");
	 }
  }

}
