/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package asint;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorSintacticoTinyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letra = 1;
  /** RegularExpression Id. */
  int digitoPositivo = 2;
  /** RegularExpression Id. */
  int digito = 3;
  /** RegularExpression Id. */
  int parteEntera = 4;
  /** RegularExpression Id. */
  int parteDecimal = 5;
  /** RegularExpression Id. */
  int parteExponencial = 6;
  /** RegularExpression Id. */
  int bool = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int real = 11;
  /** RegularExpression Id. */
  int string = 12;
  /** RegularExpression Id. */
  int and = 13;
  /** RegularExpression Id. */
  int or = 14;
  /** RegularExpression Id. */
  int not = 15;
  /** RegularExpression Id. */
  int TRUE = 16;
  /** RegularExpression Id. */
  int FALSE = 17;
  /** RegularExpression Id. */
  int NULL = 18;
  /** RegularExpression Id. */
  int proc = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int WHILE = 22;
  /** RegularExpression Id. */
  int struct = 23;
  /** RegularExpression Id. */
  int NEW = 24;
  /** RegularExpression Id. */
  int delete = 25;
  /** RegularExpression Id. */
  int read = 26;
  /** RegularExpression Id. */
  int write = 27;
  /** RegularExpression Id. */
  int nl = 28;
  /** RegularExpression Id. */
  int type = 29;
  /** RegularExpression Id. */
  int call = 30;
  /** RegularExpression Id. */
  int literalEntero = 31;
  /** RegularExpression Id. */
  int literalReal = 32;
  /** RegularExpression Id. */
  int identificador = 33;
  /** RegularExpression Id. */
  int literalCadena = 34;
  /** RegularExpression Id. */
  int suma = 35;
  /** RegularExpression Id. */
  int resta = 36;
  /** RegularExpression Id. */
  int mul = 37;
  /** RegularExpression Id. */
  int div = 38;
  /** RegularExpression Id. */
  int mod = 39;
  /** RegularExpression Id. */
  int menor = 40;
  /** RegularExpression Id. */
  int mayor = 41;
  /** RegularExpression Id. */
  int igual = 42;
  /** RegularExpression Id. */
  int distinto = 43;
  /** RegularExpression Id. */
  int menorIgual = 44;
  /** RegularExpression Id. */
  int mayorIgual = 45;
  /** RegularExpression Id. */
  int asig = 46;
  /** RegularExpression Id. */
  int finalAsig = 47;
  /** RegularExpression Id. */
  int parenApert = 48;
  /** RegularExpression Id. */
  int parenCierre = 49;
  /** RegularExpression Id. */
  int llaveApert = 50;
  /** RegularExpression Id. */
  int llaveCierre = 51;
  /** RegularExpression Id. */
  int puntoComa = 52;
  /** RegularExpression Id. */
  int coma = 53;
  /** RegularExpression Id. */
  int punto = 54;
  /** RegularExpression Id. */
  int arroba = 55;
  /** RegularExpression Id. */
  int indireccion = 56;
  /** RegularExpression Id. */
  int paramRef = 57;
  /** RegularExpression Id. */
  int corcheteApert = 58;
  /** RegularExpression Id. */
  int corcheteCierre = 59;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<parteEntera>",
    "<parteDecimal>",
    "<parteExponencial>",
    "<token of kind 7>",
    "<token of kind 8>",
    "<bool>",
    "<INT>",
    "<real>",
    "<string>",
    "<and>",
    "<or>",
    "<not>",
    "<TRUE>",
    "<FALSE>",
    "<NULL>",
    "<proc>",
    "<IF>",
    "<ELSE>",
    "<WHILE>",
    "<struct>",
    "<NEW>",
    "<delete>",
    "<read>",
    "<write>",
    "<nl>",
    "<type>",
    "<call>",
    "<literalEntero>",
    "<literalReal>",
    "<identificador>",
    "<literalCadena>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "\"&&\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"^\"",
    "\"&\"",
    "\"[\"",
    "\"]\"",
  };

}
