
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun Mar 23 18:04:11 CET 2025
//----------------------------------------------------

package c_ast_ascendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISTINTO = 47;
  public static final int LLCIERRE = 22;
  public static final int CCIERRE = 28;
  public static final int PCIERRE = 20;
  public static final int RESTA = 40;
  public static final int INT = 3;
  public static final int DELETE = 12;
  public static final int WRITE = 14;
  public static final int NOT = 35;
  public static final int AND = 33;
  public static final int IGUAL = 46;
  public static final int TYPE = 16;
  public static final int OR = 34;
  public static final int BOOL = 2;
  public static final int ARROBA = 26;
  public static final int CALL = 17;
  public static final int DIV = 42;
  public static final int LITENT = 29;
  public static final int SUMA = 39;
  public static final int IF = 7;
  public static final int INDIR = 51;
  public static final int EOF = 0;
  public static final int ASIG = 50;
  public static final int TRUE = 36;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int LITREAL = 30;
  public static final int MUL = 41;
  public static final int COMA = 24;
  public static final int MENOR = 44;
  public static final int NULL = 38;
  public static final int MOD = 43;
  public static final int PCOMA = 23;
  public static final int MAYOR = 45;
  public static final int REAL = 4;
  public static final int PAPERT = 19;
  public static final int ELSE = 8;
  public static final int PUNTO = 25;
  public static final int MAYORIG = 49;
  public static final int NL = 15;
  public static final int READ = 13;
  public static final int IDEN = 32;
  public static final int WHILE = 9;
  public static final int PARAMREF = 27;
  public static final int MENORIG = 48;
  public static final int LLAPERT = 21;
  public static final int PROC = 6;
  public static final int STRING = 5;
  public static final int LITCADENA = 31;
  public static final int FALSE = 37;
  public static final int STRUCT = 10;
  public static final int CAPERT = 52;
  public static final int FINALASIG = 18;
}

